language: python

dist: xenial

os: linux

python:
  - "3.9"

services:
  - mysql

env:
  - DJANGO_VERSION=3.2.9 CYBERWARY_SECRET="SECRET_FOR_TESTING" CYBERWARY_MYSQL_DB="cyberwary_test" CYBERWARY_MYSQL_USER="root" CYBERWARY_MYSQL_PASSWORD="" CYBERWARY_MYSQL_HOST="127.0.0.1" CYBERWARY_MYSQL_PORT="3306"
  
before_install:
  - python -m pip install --upgrade pip
  - mysql -e 'CREATE DATABASE cyberwary_test;'

install:
  - pip3 install -r requirements.txt
  - python3 manage.py migrate

script:
  - python3 manage.py test