# Generated by Django 4.0.2 on 2022-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_wary_portal', '0002_initial_data_structure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='antivirus_product',
            new_name='installed_antivirus',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='firewall_rules',
            new_name='network_firewall_rules',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='browser_passwords',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='outdated_applications',
        ),
        migrations.AddField(
            model_name='scan',
            name='installed_firmware',
            field=models.BooleanField(default=False, help_text='Flag for scan of installed firmware and drivers.', null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='installed_patches',
            field=models.BooleanField(default=False, help_text='Flag for scan of installed OS updates and patches.', null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='network_exposure',
            field=models.BooleanField(default=False, help_text='Flag for scan of network exposure.', null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='system_services',
            field=models.BooleanField(default=False, help_text='Flag for scan of system services.', null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='system_passwords',
            field=models.BooleanField(default=False, help_text='Flag for scan of passwords stored on the system.', null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='title',
            field=models.CharField(help_text='An identifier for a scan.', max_length=32, null=True),
        ),
    ]
