# Generated by Django 3.2.9 on 2021-12-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_wary_portal', '0002_default_scan_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='system_password',
            new_name='system_passwords',
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_key',
            field=models.CharField(help_text='A unique key associated with the scan.', max_length=32),
        ),
        migrations.AlterField(
            model_name='scan',
            name='title',
            field=models.CharField(default='Untitled Scan', help_text='An identifier for a scan.', max_length=32, null=True),
        ),
    ]
