# Generated by Django 4.0.2 on 2022-03-21 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_wary_portal', '0004_scan_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialrecord',
            name='password_strength',
            field=models.IntegerField(choices=[(1, 'Very Weak'), (2, 'Weak'), (3, 'Medium'), (4, 'Strong'), (5, 'Very Strong')], default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('full_name', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('sid', models.CharField(max_length=48, null=True)),
                ('source', models.IntegerField(choices=[(1, 'Local'), (2, 'Microsoft')], default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('enabled', models.BooleanField(default=False)),
                ('last_logon', models.DateTimeField(null=True)),
                ('password_changeable', models.DateTimeField(null=True)),
                ('password_expiry', models.DateTimeField(null=True)),
                ('password_permission', models.BooleanField(default=False)),
                ('password_required', models.BooleanField(default=False)),
                ('password_last_set', models.DateTimeField(null=True)),
                ('scan_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyber_wary_portal.scanrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
