# Generated by Django 4.0.2 on 2022-03-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_wary_portal', '0007_update_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='The title of an update (Title).', max_length=256, null=True)),
                ('description', models.CharField(help_text='The description that accompanies the update (Description).', max_length=1024, null=True)),
                ('install_deadline', models.DateTimeField(help_text='The date/time that the install is required to be installed by (Deadline).', null=True)),
                ('eula_accepted', models.BooleanField(default=False, help_text='The flag to confirm that the EULA has been accepted by the user (EulaAccepted).')),
                ('beta', models.BooleanField(default=False, help_text='The flag to indicate that the update is in BETA (IsBeta).')),
                ('downloaded', models.BooleanField(default=False, help_text='The flag to indicate that the update has been already downloaded (IsDownloaded).')),
                ('hidden', models.BooleanField(default=False, help_text='The flag to indicate that the update is hidden from the end user (IsHidden).')),
                ('mandatory', models.BooleanField(default=False, help_text='The flag to indicate that the update is mandatory to be installed (IsMandatory).')),
                ('uninstallable', models.BooleanField(default=False, help_text='The flag to indicate that the update is able to be individually uninstalled (IsMandatory).')),
                ('reboot_required', models.BooleanField(default=False, help_text='The flag to indicate that the update will require a restart to install (RebootRequired).')),
                ('date_check', models.DateTimeField(help_text='The date/time that the update was last checked (LastDeploymentChangeTime).', null=True)),
                ('download_size', models.IntegerField(default=0, help_text='The maximum download/install size for the update (MaxDownloadSize).', null=True)),
                ('security_rating', models.CharField(help_text='The security severity rating for the update (MsrcSeverity).', max_length=32, null=True)),
                ('cves', models.CharField(help_text='The list of CVEs associated with the update (CveIDs).', max_length=128, null=True)),
                ('driver_date', models.CharField(help_text='The date that the driver/update was released (DriverVerDate).', max_length=128, null=True)),
                ('driver_manufacturer', models.CharField(help_text='The software developer of the driver/update (DriverProvider).', max_length=128, null=True)),
                ('driver_model', models.CharField(help_text='The device that the update/firmware/driver is for (DriverModel).', max_length=128, null=True)),
                ('scan_record', models.ForeignKey(help_text='The scan record that the Windows Defender detection is associated with.', on_delete=django.db.models.deletion.CASCADE, to='cyber_wary_portal.scanrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateInstalled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(help_text='The date/time that the update was installed (Date).', null=True)),
                ('title', models.CharField(help_text='The title of an update (Title).', max_length=256, null=True)),
                ('description', models.CharField(help_text='The description that accompanies the update (Description).', max_length=1024, null=True)),
                ('kb', models.CharField(help_text='The microsoft KB identifier (KB).', max_length=16, null=True)),
                ('result', models.CharField(help_text='The status of the installation (Result).', max_length=16, null=True)),
                ('scan_record', models.ForeignKey(help_text='The scan record that the Windows Defender detection is associated with.', on_delete=django.db.models.deletion.CASCADE, to='cyber_wary_portal.scanrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
