# Generated by Django 4.0.2 on 2022-03-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_wary_portal', '0010_firewall_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='startup_applications',
        ),
        migrations.RemoveField(
            model_name='software',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='software',
            name='system_component',
        ),
        migrations.AddField(
            model_name='biosinstall',
            name='install_status',
            field=models.CharField(help_text='The status of the BIOS.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='biosinstall',
            name='primary',
            field=models.CharField(help_text='The status for the OS being the primary installed.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='cpe',
            field=models.ForeignKey(default=None, help_text='The CPE associated with the application.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cyber_wary_portal.cpe'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(help_text='The name given to the software (Name).', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='firewallrules',
            name='group',
            field=models.CharField(help_text='The group that the firewall rule is associated with (Group).', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='firewallrules',
            name='local_port',
            field=models.CharField(help_text='The local port number that the rule targets (LocalPort).', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='firewallrules',
            name='name',
            field=models.CharField(help_text='The display name of the firewall rule (DisplayName).', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='firewallrules',
            name='remote_port',
            field=models.CharField(help_text='The remote port number that the rule targets (RemotePort).', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='firewallrules',
            name='rule_id',
            field=models.CharField(help_text='The instance ID associated with the firewall rule (ID/InstanceID).', max_length=128, null=True),
        ),
        migrations.RenameField(
            model_name='language',
            old_name='string',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='firewallrules',
            name='enabled',
            field=models.IntegerField(default=0, help_text='The enabled status of the rule (Enabled).'),
        ),
        migrations.AlterField(
            model_name='updatepending',
            name='download_size',
            field=models.BigIntegerField(default=0, help_text='The maximum download/install size for the update (MaxDownloadSize).', null=True),
        ),
        migrations.AlterField(
            model_name='updatepending',
            name='uninstallable',
            field=models.BooleanField(default=False, help_text='The flag to indicate that the update is able to be individually uninstalled (IsUninstallable).'),
        ),
    ]
