# Generated by Django 4.0.2 on 2022-03-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_wary_portal', '0010_firewall_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='startup_applications',
        ),
        migrations.RemoveField(
            model_name='software',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='software',
            name='system_component',
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(help_text='The name given to the software (Name).', max_length=128, null=True),
        ),
    ]
