# Generated by Django 4.0.2 on 2022-04-15 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_wary_portal', '0011_field_alterations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defenderdetection',
            old_name='reseponse_type',
            new_name='response_type',
        ),
        migrations.AlterField(
            model_name='defenderpreference',
            name='dns_sinkhole',
            field=models.BooleanField(default=False, help_text='The flag to identify if DNS sinkhole on malicious traffic detection has been enabled (EnableDnsSinkhole).'),
        ),
        migrations.AlterField(
            model_name='defenderdetection',
            name='response_type',
            field=models.IntegerField(choices=[(1, 'Extension'), (2, 'Ip Address'), (3, 'Path'), (4, 'Process')], default=1, help_text='The type of response that was taken to the threat detection (CleaningActionID).', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='WindowsUser',
        ),
    ]
