# Generated by Django 4.0.2 on 2022-04-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_wary_portal', '0011_field_alterations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defenderdetection',
            old_name='reseponse_type',
            new_name='response_type',
        ),
        migrations.AlterField(
            model_name='defenderpreference',
            name='dns_sinkhole',
            field=models.BooleanField(default=False, help_text='The flag to identify if DNS sinkhole on malicious traffic detection has been enabled (EnableDnsSinkhole).'),
        ),
    ]
